/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtuacaoRouteImport } from './routes/atuacao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as DuvidasRouteImport } from './routes/duvidas'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AtuacaoIndexRouteImport } from './routes/atuacao.index'
import { Route as AtuacaoDireitoPenalRouteImport } from './routes/atuacao.direito-penal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoRoute = AtuacaoRouteImport.update({
  id: '/atuacao',
  path: '/atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const DuvidasRoute = DuvidasRouteImport.update({
  id: '/duvidas',
  path: '/duvidas',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoIndexRoute = AtuacaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtuacaoRoute,
} as any)
const AtuacaoDireitoPenalRoute = AtuacaoDireitoPenalRouteImport.update({
  id: '/direito-penal',
  path: '/direito-penal',
  getParentRoute: () => AtuacaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/duvidas': typeof DuvidasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/atuacao/direito-penal': typeof AtuacaoDireitoPenalRoute
  '/atuacao/': typeof AtuacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/duvidas': typeof DuvidasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/atuacao/direito-penal': typeof AtuacaoDireitoPenalRoute
  '/atuacao': typeof AtuacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/duvidas': typeof DuvidasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/atuacao/direito-penal': typeof AtuacaoDireitoPenalRoute
  '/atuacao/': typeof AtuacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atuacao'
    | '/contato'
    | '/conteudos'
    | '/duvidas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/atuacao/direito-penal'
    | '/atuacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/conteudos'
    | '/duvidas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/atuacao/direito-penal'
    | '/atuacao'
  id:
    | '__root__'
    | '/'
    | '/atuacao'
    | '/contato'
    | '/conteudos'
    | '/duvidas'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/atuacao/direito-penal'
    | '/atuacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtuacaoRoute: typeof AtuacaoRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ConteudosRoute: typeof ConteudosRoute
  DuvidasRoute: typeof DuvidasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao': {
      id: '/atuacao'
      path: '/atuacao'
      fullPath: '/atuacao'
      preLoaderRoute: typeof AtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duvidas': {
      id: '/duvidas'
      path: '/duvidas'
      fullPath: '/duvidas'
      preLoaderRoute: typeof DuvidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/': {
      id: '/atuacao/'
      path: '/'
      fullPath: '/atuacao/'
      preLoaderRoute: typeof AtuacaoIndexRouteImport
      parentRoute: typeof AtuacaoRoute
    }
    '/atuacao/direito-penal': {
      id: '/atuacao/direito-penal'
      path: '/direito-penal'
      fullPath: '/atuacao/direito-penal'
      preLoaderRoute: typeof AtuacaoDireitoPenalRouteImport
      parentRoute: typeof AtuacaoRoute
    }
  }
}

interface AtuacaoRouteChildren {
  AtuacaoDireitoPenalRoute: typeof AtuacaoDireitoPenalRoute
  AtuacaoIndexRoute: typeof AtuacaoIndexRoute
}

const AtuacaoRouteChildren: AtuacaoRouteChildren = {
  AtuacaoDireitoPenalRoute: AtuacaoDireitoPenalRoute,
  AtuacaoIndexRoute: AtuacaoIndexRoute,
}

const AtuacaoRouteWithChildren =
  AtuacaoRoute._addFileChildren(AtuacaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtuacaoRoute: AtuacaoRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ConteudosRoute: ConteudosRoute,
  DuvidasRoute: DuvidasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
